# Generated by Django 4.1.3 on 2023-03-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='supplier',
        ),
    ]
