# Generated by Django 4.1.3 on 2023-03-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationline',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='supplier',
        ),
    ]
