# Generated by Django 4.1.3 on 2023-03-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
        ('quotation', '0003_rename_product_id_quotationline_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AddField(
            model_name='quotation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QuotationLine',
        ),
    ]
