# Generated by Django 4.1.3 on 2023-03-23 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0006_alter_quotation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partner.district'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
