# Generated by Django 4.1.3 on 2023-03-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_initial'),
        ('quotation', '0007_remove_quotationline_quotation_quotation_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='partner.district'),
        ),
    ]
