# Generated by Django 4.1.3 on 2023-03-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_alter_quotation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
        ),
    ]
