# Generated by Django 4.1.3 on 2023-03-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_alter_quotationline_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='created_by',
        ),
    ]
